# BUILD Settings:
# ##############################################################################
[build]
  publish = "public"
  functions = "lambda"

[dev]
  publish = "public"
  port = 64946
  autolaunch = true

# HEADERS - BASIC AUTH
# ##############################################################################
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "form-action https:"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    Permissions-Policy = "vibrate=(), geolocation=(), midi=(), notifications=(), push=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), speaker=(), vibrate=(), fullscreen=()"

# REDIRECTS are located here
# ###############################################################################
[[redirects]]
  from = "/api/*"
  to = ".netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/my-test-redirect"
  to = "/page-1"
  status = 301

[[redirects]]
  from = "/redirect/page-2"
  to = "/page-2"
  status = 301

[[redirects]]
  from = "/get/page/help/contact-us"
  to = "/contact-us"
  status = 301

[[redirects]]
  from = "/get/page/life-long-learning/book-overview"
  to = "/book-overview"
  status = 301

# Wildcard for anything. 
[[redirects]]
  from = "*"
  to = "https://pg-dev.stanford.edu/:splat"
  status = 301
  headers = { X-From = "Netlify" }